# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods

end

target 'eoswallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eoswallet

  #target 'eoswallet-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

  common_pods

  target 'eoswalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eoswallet-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eoswallet-tvOS

  target 'eoswallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
