# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
def common_pods

end

target 'eoswallet' do
  project 'eoswallet.xcodeproj'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eoswallet

  #target 'eoswallet-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

  common_pods

pod 'rn-splash-screen', :path => '../node_modules/rn-splash-screen'

#  target 'eoswalletTests' do
#    inherit! :search_paths
    # Pods for testing
#  end

end


